### ISSUE TITLE
when does code release?  And please release pre-computed result on davis and youtube.

### ISSUE THREAD

**Issue by shoutOutYangJie** [HYOJINPARK/Reuse_VOS#1]

**Comment by HYOJINPARK** [comment]
@shoutOutYangJie 
Thanks for your interest.
I wait for approval from Facebook, and I will release the overall code on Apr 1.

**Comment by shoutOutYangJie** [comment]
thank you. I wish you do not fool me at&nbsp;April Fools' Day



------------------ Original ------------------
From: HYOJINPARK ***@***.***&gt;
Date: Mon,Mar 22,2021 11:44 PM
To: HYOJINPARK/Reuse_VOS ***@***.***&gt;
Cc: shoutOutYangJie ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [HYOJINPARK/Reuse_VOS] when does code release?  And please release pre-computed result on davis and youtube. (#1)





 
@shoutOutYangJie
 Thanks for your interest.
 I wait for approval from Facebook, and I will release the overall code on Apr 1.

**Comment by HYOJINPARK** [comment]
@shoutOutYangJie 
Oh my!! haha, plz no worry.
Just due date of CVPR camera-ready is 3/29 and 3 days margin for me.
Thanks ^^
