### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by longmalongma** [HYOJINPARK/Reuse_VOS#2]
![image](https://user-images.githubusercontent.com/40291722/114271256-0efed480-9a43-11eb-84bf-7f9aa0ff147d.png)

Thank you for your great work. Can you help me solve this problem when I repeat your code?

**Comment by HYOJINPARK** [comment]
@longmalongma 
sorry for the late answer due to preparing my Ph.D. defense.
I checked my code again but I don't have the problem
Did you chance path in train.py regarding your data path?
Also, I use python 3.6, not 3.8

**Comment by longmalongma** [comment]
> @longmalongma
> sorry for the late answer due to preparing my Ph.D. defense.
> I checked my code again but I don't have the problem
> Did you chance path in train.py regarding your data path?
> Also, I use python 3.6, not 3.8

Yes, I got it, thanks!
