### ISSUE TITLE
Which line of your code reflects Refine-translator?

### ISSUE THREAD

**Issue by longmalongma** [HYOJINPARK/Reuse_VOS#3]
Which line of your code reflects Refine-translator?

**Comment by HYOJINPARK** [comment]
Hi @longmalongma 
Thanks for asking
plz, check /model/seg_network.py
line 196 and line 233-235

Thanks

**Comment by longmalongma** [comment]
> Hi @longmalongma
> Thanks for asking
> plz, check /model/seg_network.py
> line 196 and line 233-235
> 
> Thanks

Thanks for your reply, I got it!
