### ISSUE TITLE
What exactly do templates refer to in template matching

### ISSUE THREAD

**Issue by longmalongma** [HYOJINPARK/Reuse_VOS#4]
![image](https://user-images.githubusercontent.com/40291722/116531153-72c54080-a911-11eb-8172-bbb00dac419b.png)

I would like to ask the following questions: 1. What exactly do templates refer to in template matching; 2. Refine-translator is added after backbone?

**Comment by HYOJINPARK** [comment]
Hi @longmalongma 
Thanks for asking.

![diagram](https://user-images.githubusercontent.com/24826943/116807589-f4fe7080-ab6e-11eb-89e8-5e1d0befbf9e.png)

The 'template' has target information and embeds A, C region as a dissimilarity map (D_t).
Actually, I did not mention this detailed motivation in my paper....
I conjecture that:
    
      When a target moves from red to blue region, the S_(t-n) gives attention to the red region (A+B).
      Therefore, we know where is A + B region in f8_t
      However,  the real target information is located in B + C region inside of f8_t.
      Therefore, B has strong target information (attention from S_t-n and target feature),
      and C (target feature) has less strong target information.
      The template matching uses the 'template' and recognizes the B and C region from f8_t.
      So finally, we can know and divide where is B and C regions,
      and creates a dissimilarity map (D_t) for A and C region.

Yes, refine-translator is added after backbone (feature extractor)
You can insert refine-translator middle of generating mask (refined network).
Please let me know if you have further questions.
